include: package:surf_lint_rules/analysis_options.yaml
linter:
  rules:
    avoid_print: false
    implicit-dynamic: false
    invalid_annotation_target: ignore

analyzer:
  exclude:
    - lib/**/*.g.dart